In [1]:
import numpy as np

In [2]:
np.eye?

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of 

In [6]:
x = np.array([2,3,5,1]) # 1D ARRAY
x2d = np.array([[1,2,3],[4,5,6]]) # 2D ARRAY
x3d = np.array([[[1,3],[4,5]],[[6,7],[2,1]]])
print(x)
print(x2d)
print(x3d)

[2 3 5 1]
[[1 2 3]
 [4 5 6]]
[[[1 3]
  [4 5]]

 [[6 7]
  [2 1]]]


In [8]:
# sequential matrix, np.arange() and np.linspace()
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [9]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x105dea480>
File:            ~/miniconda3/lib/python3.11/site-packages/numpy/core/function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of 

In [12]:
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [13]:
np.arange(0,10,0.2).size

50

In [14]:
np.arange(0,10,0.2).reshape(5,10) # 2d

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [19]:
np.linspace(0,15,10)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

In [21]:
np.linspace(0,15,10).size

10

In [22]:
np.linspace(0,15,10).reshape(5,2)

array([[ 0.        ,  1.66666667],
       [ 3.33333333,  5.        ],
       [ 6.66666667,  8.33333333],
       [10.        , 11.66666667],
       [13.33333333, 15.        ]])

In [29]:
# randomized matrix with np.random
# np.random.rand()
print(np.random.rand(4,4))    # 0 to 1
print(np.random.rand(3,3))    # normal distribution
print(np.random.randint(-10,10,(3,3)))  # random int from -10 to 10
print(np.random.uniform(0,2,(3,3)))   # random float from 0 to 10
print(np.random.permutation([1,2,3,4,5,6,7,8,9,10]))  # random permutation

[[0.21976021 0.22479065 0.2456884  0.61560566]
 [0.65704741 0.5200933  0.99036426 0.18487702]
 [0.49338251 0.65071912 0.02086958 0.95828324]
 [0.7965385  0.38441736 0.00266533 0.78819587]]
[[0.99280773 0.86343384 0.17347114]
 [0.15451044 0.42549544 0.73684424]
 [0.09088913 0.51868043 0.55467349]]
[[ 5 -1 -2]
 [-4 -2 -5]
 [-1  7 -1]]
[[0.93151885 0.62130518 0.26133354]
 [1.45873574 1.59985235 1.50051699]
 [0.91347612 1.93804586 0.74927743]]
[ 5  7  4  3  9  1  6  2 10  8]


operations

In [30]:
a = np.random.randint(-10,10,(3,3))
b = np.random.randint(-10,10,(3,3))
print(a)
print(b)

[[  3   6   1]
 [ -7 -10  -8]
 [  8   5   2]]
[[ -2  -6   3]
 [  0  -6 -10]
 [ -8  -6   6]]


In [31]:
a * 10 # + - * / ** % //

array([[  30,   60,   10],
       [ -70, -100,  -80],
       [  80,   50,   20]])

In [32]:
# same size mart operations
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a@b)

[[  1   0   4]
 [ -7 -16 -18]
 [  0  -1   8]]
[[ 5 12 -2]
 [-7 -4  2]
 [16 11 -4]]
[[-1.5        -1.          0.33333333]
 [       -inf  1.66666667  0.8       ]
 [-1.         -0.83333333  0.33333333]]
[[ -6 -36   3]
 [  0  60  80]
 [-64 -30  12]]
[[-14 -60 -45]
 [ 78 150  31]
 [-32 -90 -14]]


/var/folders/dy/k_2mc4t13bvg7g2rjf5bx3c00000gn/T/ipykernel_2247/846531082.py:4: RuntimeWarning: divide by zero encountered in divide
  print(a/b)


In [33]:
np.matmul(a,b) # np.dot(a,b) or a@b

array([[-14, -60, -45],
       [ 78, 150,  31],
       [-32, -90, -14]])